---

XGUI:
  xsession_path: /usr/bin/xinit
  xterm_path: /usr/bin/Xorg
  vnc_dependencies:
    - xterm
    - git
  packages_to_remove:
    - realvnc-vnc-server
  packages:
    - xorg-x11-xauth
    - tigervnc-server
    - novnc
