---

XGUI:
  xsession_path: /usr/bin/xinit
  xterm_path: /usr/bin/xterm
  vnc_dependencies:
    - xterm 
    - git
  packages_to_remove:
    - realvnc-vnc-server
  packages:
    - xorg-x11-xauth
    - vnc-server
