---

XGUI:
  xsession_path: /usr/bin/X
  xterm_path: /usr/bin/xinit
  vnc_dependencies:
    - libfam0
    - libxext-dev 
    - libx11-dev 
    - libc6-dev 
    - libthunar-vfs-1-2 
    - libc6
  packages_to_remove:
    - realvnc-vnc-server
    - novnc
  packages:
    - vnc4server
