---

XGUI:
  xsession_path: /usr/bin/X
  xterm_path: /usr/bin/xinit
  vnc_dependencies:
    - libfam0
    - libxext-dev 
    - libx11-dev 
    - libc6-dev 
    - libthunar-vfs-1-2 
    - libc6
    - git
  packages_to_remove:
    - realvnc-vnc-server
    - novnc
  packages:
    - vnc4server

VNC_COMMANDS:
  - /bin/su {{ ATMOUSERNAME }} -c "/usr/bin/printf '%s\n%s\n' 'display' 'display' | vncpasswd /home/{{ ATMOUSERNAME }}/.vnc/passwd"
  - "/usr/bin/pkill websockify"
  - "for i in $(/usr/bin/pgrep -f '/opt/kanaka-noVNC-8b0a0f6/utils/');do /bin/echo 'killing process:' $i; /bin/kill -HUP $i;done"
  - "/bin/su {{ ATMOUSERNAME }} -c '/usr/bin/vncserver -localhost :1'"
  - "/opt/kanaka-noVNC-8b0a0f6/utils/launch.sh --listen 4200 --vnc localhost:5901 &"
