---
- name: Playbook updates package manager and installs atmosphere dependencies
  hosts: all
  roles:
    - fix-centos6-networking
    - atmo-ntp
    - { role: atmo-dhcp, when: SETUP_DHCP_CLIENT is defined and SETUP_DHCP_CLIENT == true }
    - { role: ldap, when: SETUP_LDAP is defined and SETUP_LDAP == true }
    - atmo-fail2ban
