# This file assumes SSHKEYS and use_remote_user

- name: task to clear the tty from suoers
  raw: sed -i '/^Defaults\s*requiretty/d' /etc/sudoers
  become: true
  remote_user: "{{ use_remote_user }}"

- name: remove the standard cloud disable command
  lineinfile: dest=/root/.ssh/authorized_keys state=absent regexp="command\="
  become: true
  remote_user: "{{ use_remote_user }}"

- name: add ssh keys to authorized_keys
  authorized_key: user=root key="{{ item }}" state=present
  become: true
  remote_user: "{{ use_remote_user }}"
  with_items: '{{ SSHKEYS }}'
  when: SSHKEYS is defined

- name: remove ssh keys from authorized_keys
  authorized_key: user=root key="{{ item }}" state=absent
  become: true
  remote_user: "{{ use_remote_user }}"
  with_items: '{{ SSH_KEYS_TO_REMOVE }}'
  when: SSH_KEYS_TO_REMOVE is defined
