- name: check for x64 foreign architecture
  shell: dpkg --print-foreign-architectures | grep x64
  register: x64_arch_exists
  failed_when: False
  when: ansible_distribution == "Ubuntu"

- name: if x64 found, remove x64 architecture
  shell: dpkg --remove-architecture x64
  when: ansible_distribution == "Ubuntu" and x64_arch_exists is success

- name: if x64 found, add amd64
  shell: dpkg --add-architecture amd64
  when: ansible_distribution == "Ubuntu" and x64_arch_exists is success

- name: apt-get update
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  failed_when: False
  tags: update

# block for centos tasks
- block:

  - name: disable an old sensu repo if present
    yum_repository:
      name: sensu
      state: absent
    notify: yum clean metadata

  # this will cause the handler to execute at this point, if pending rather than at the end of playbook
  - meta: flush_handlers

  # for now, leave this in since ansible yum update-cache is super slow in older version of ansible
  - name: yum check-update
    shell: yum check-update
    failed_when: False
    tags: update

  when: ansible_distribution == "CentOS"
