---

SUDOERS_USERS_AND_GROUPS:
  TO_ADD:
    users:
      line: "%users ALL=(ALL) ALL"
      reg: "^%users\\s+ALL=\\(ALL\\)\\s*ALL"
    atmouser:
      line: "{{ ATMOUSERNAME }} ALL=(ALL) ALL"
      reg: "^{{ ATMOUSERNAME }}\\s+ALL=\\(ALL\\)\\s*ALL"
  TO_REMOVE:
    users:
      line: "%users ALL=(ALL) NOPASSWD:ALL"
      reg: "^%users\\s*ALL=\\(ALL\\)\\s*NOPASSWD:ALL"
    atmouser_dupe:
      line: "{{ ATMOUSERNAME }} ALL=(ALL) ALL"
      reg: "^{{ ATMOUSERNAME }}\\s+ALL=\\(ALL\\)\\s*ALL"
    atmouser_nopass:
      line: "{{ ATMOUSERNAME }} ALL=(ALL) NOPASSWD:ALL"
      reg: "^{{ ATMOUSERNAME }}\\s+ALL=\\(ALL\\)\\s*NOPASSWD:ALL"

SETUP_USER_BASHRC_LINES: []

ADD_TO_GROUP:
  GROUP: users
  LIST_OF_USERS:
    - '{{ ATMOUSERNAME }}'

MAKE_SUDO: False
