---

vncserver_pkg: 'VNC-Server-5.2.3-Linux-x64.deb'

XGUI:
  xsession_path: /usr/bin/X
  xterm_path: /usr/bin/xinit
  packages_to_remove:
    - vnc4server
  files_to_add:
    - { FROM: '{{ vncserver_pkg }}', TO: '/tmp/{{ vncserver_pkg }}' }
    - { FROM: vncserver.custom, TO: /etc/pam.d/vncserver.custom }
    - { FROM: common.custom, TO: /etc/vnc/config.d/common.custom }
