---
- name: Copy desktop background to instance
  copy:
    src: "{{ background_img }}"
    dest: /usr/share/backgrounds/cloud_background.jpg

- name: Check for /etc/xfce
  stat:
    path: '/usr/bin/xfconf-query'
  register: xfce

- name: Set change_background_cmd for Gnome
  set_fact:
    change_background_cmd: 'gconftool-2 -s -t string /desktop/gnome/background/picture_filename "/usr/share/backgrounds/cloud_background.jpg"'
  when: not xfce.stat.exists

- name: Set change_background_cmd for XFCE
  set_fact:
    change_background_cmd: 'xfconf-query -c xfce4-desktop --property /backdrop/screen0/monitor0/workspace0/last-image --set /usr/share/backgrounds/cloud_background.jpg'
  when: xfce.stat.exists

- name: Change desktop background
  become: yes
  become_user: "{{ ATMOUSERNAME }}"
  command: '{{ change_background_cmd }}'
