---

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: copy globus-connect client to remote host
  copy: src=globusconnectpersonal-latest.tgz dest=/opt/globusconnectpersonal.tgz
  tags: install

- name: unarchive globus-connect client
  unarchive: src=/opt/globusconnectpersonal.tgz dest=/opt/ copy=no
  tags: install

- name: remove tar after unarchive
  file: path=/opt/globusconnectpersonal.tgz state=absent
  tags:
    - install
    - remove

- name: template bash profile.d with globus-connect path
  template: src=globus-connect-profile.j2 dest=/etc/profile.d/globus-connect.sh mode=0755
  tags: configure

# - name: add globus endpoint
#   shell: /bin/su {{ ATMOUSERNAME }} -c endpoint-add -n {{ GLOBUS_ENDPOINT }} --gc
#   delegate_to: globus
#   register: endpoint_id
#   failed_when: False
#   tags: user

# - name: print endpoint id
#   debug: var=endpoint_id

- name: run globus setup
  shell: /bin/su {{ ATMOUSERNAME }} -c globusconnect -setup {{ GLOBUS_SETUP_KEY }}
  failed_when: False
  tags: user

- name: start up globusconnect
  shell: /bin/su {{ ATMOUSERNAME }} -c globusconnect -start &
  failed_when: False
  tags: user
