---

- name: stop denyhosts
  service: name=denyhosts state=stopped enabled=no
  ignore_errors: yes
  failed_when: False

- name: uninstall denyhosts
  yum: name=denyhosts.noarch state=absent
  tags: uninstall-denyhosts

- name: install dependencies
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - iptables
    - iptables-services
    - iptables-utils
    - policycoreutils-python
  tags: install-dependencies

- name: install fail2ban for centos7
  yum: name=fail2ban state=present
  tags: install-fail2ban

- name: configure fail2ban local jails
  action: template src=centos7-jail.local.j2 dest=/etc/fail2ban/jail.local mode=0644
  tags: configure-fail2ban

- name: disable and stop firewalld
  service: name=firewalld state=stopped enabled=no
  tags: stop-firewalld

- name: enable and start iptables
  service: name=iptables state=started enabled=yes
  tags: start-and-enable-iptables

- name: restart ssh
  service: name=sshd state=restarted
  tags: restart-ssh

- name: restart fail2ban service
  service: name=fail2ban state=restarted enabled=yes
  tags: restart-fail2ban

- name: configure iptables
  action: template src=centos7-iptables.j2 dest=/etc/sysconfig/iptables mode=0600
  tags: configure-iptables
  notify: restart iptables centos7

