- name: uninstall denyhosts
  apt: name=denyhosts.noarch state=absent purge=yes
  tags: uninstall-denyhosts

- name: install fail2ban for Ubuntu
  apt: name=fail2ban state=present force=yes
  tags: install-fail2ban

- name: configure fail2ban local jails
  action: template src=ubuntu-jail.local.j2 dest=/etc/fail2ban/jail.local mode=0644
  notify: restart fail2ban ubuntu
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version < '15'
  tags: configuration

- name: configure fail2ban local jails
  action: template src={{ item }} dest=/etc/fail2ban/jail.local mode=0644
  notify: restart fail2ban ubuntu
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '15'
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.jail.local.j2"
    - "{{ ansible_distribution }}.jail.local.j2"

- name: restart fail2ban service
  service: name=fail2ban state=restarted enabled=yes
  tags: restart-fail2ban
