---

- name: Checking for necessary --extra_vars
  hosts: all
  vars:
    example:
        - "-e \"{'VOLUME_MOUNT_LOCATION':'/vol-b'}\""

  tasks:

    - fail: msg="Variable VOLUME_MOUNT_LOCATION is not set."
      when: VOLUME_MOUNT_LOCATION is not defined

- name: Play to unmount a volume
  hosts: atmosphere
  roles:
    - atmo-unmount-volume
