---

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: os-vars

- name: get hostname set by dhcp script
  shell: hostname
  register: dhcp_hostname

- name: state which host will be added
  debug: msg="Add /etc/hosts entry for {{ dhcp_hostname.stdout }}"

- name: add FQDN hostname to /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ dhcp_hostname.stdout }}' owner=root group=root mode=0644
  tags: hostname
