---
# defaults file for atmo-novnc

REQUIRED:
  files_to_add:
    - { FROM: passwd, TO: "/home/{{ ATMOUSERNAME }}/.vnc/passwd" }
    #- { FROM: , TO:  }
  files_to_remove:
    - { PATH: /tmp/.X1-lock, STATE: absent }
    - { PATH: /tmp/.X11-unix, STATE: absent }
    - { PATH: /tmp/VNC-Server-5.2.3-Linux-x64.rpm, STATE: absent }
    - { PATH: /tmp/VNC-Server-5.2.3-Linux-x64.deb, STATE: absent }
    - { PATH: /opt/VNC-Server-5.2.3-Linux-x64.rpm, STATE: absent }
    - { PATH: /opt/VNC-Server-5.2.3-Linux-x64.deb, STATE: absent }
    - { PATH: /tmp/novnc.tar, STATE: absent }
    - { PATH: /etc/pam.d/vncserver.custom, STATE: absent }
    - { PATH: /etc/vnc/config.d/common.custom, STATE: absent }
    - { PATH: /etc/vnc/config.custom, STATE: absent }
  dirs_to_make:
    - { PATH: /tmp/.X11-unix, STATE: directory, MODE: "a+rwxt" }
    - { PATH: "/home/{{ ATMOUSERNAME }}", STATE: directory, MODE: "0750" }

VNC_COMMANDS:
  - /bin/su {{ ATMOUSERNAME }} -c "/usr/bin/printf '%s\n%s\n' 'display' 'display' | vncpasswd /home/{{ ATMOUSERNAME }}/.vnc/passwd"
  - "/usr/bin/pkill websockify"
  - "for i in $(/usr/bin/pgrep -f '/opt/kanaka-noVNC-8b0a0f6/utils/');do /bin/echo 'killing process:' $i; /bin/kill -HUP $i;done"
  - "/bin/su {{ ATMOUSERNAME }} -c '/usr/bin/vncserver -localhost :1'"
  - "websockify -D --web /usr/share/novnc/ 4200 localhost:5901"
