---

- name: Set MOUNT_OPTS Ubuntu < 16
  set_fact:
    MOUNT_OPTS: 'nobootwait'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version < "16"

- name: Debug ansible devices
  debug:
    var: item
  with_items: '{{ ansible_devices }}'

- name: Debug ansible mounts
  debug:
    var: item
  with_items: '{{ ansible_mounts }}'

- name: 'Mount volume using ansible module'
  mount:
    fstype: '{{ VOLUME_DEVICE_TYPE }}'
    src: '{{ VOLUME_DEVICE }}'
    state: 'mounted'
    path: '{{ VOLUME_MOUNT_LOCATION }}'
    passno: '{{ VOLUME_PASSNO }}'
    opts: '{{ VOLUME_OPTS }}'
  register: mount_result

- name: Debug mount result
  debug:
    var: mount_result

- name: Change directory ownership
  file:
    state: directory
    path: "{{ VOLUME_MOUNT_LOCATION }}"
    recurse: yes
    owner: "{{ ATMOUSERNAME }}"
    group: "{{ ATMO_USER_GROUP }}"
