LDAP_CONF_PATH: /etc/ldap.conf

LDAP_AUTHCONFIG: authconfig --enableldap --enableldapauth --ldapserver=ldap.iplantc.org --ldapbasedn="ou=People,dc=iplantcollaborative,dc=org" --enablelocauthorize --update

LDAP_SERVICE: nscd

TEST_LDAP_USER: mattd-test01
