LDAP_CONF_PATH: /etc/ldap.conf

#SSSD_CONF_PATH: /etc/sssd/sssd.conf

#LDAP_AUTHCONFIG: authconfig --enableldap --enableldapauth --enablemkhomedir --enablesssd --enablesssdauth --ldapserver=ldap.iplantc.org --ldapbasedn="dc=iplantcollaborative,dc=org" --passalgo=md5 --update

LDAP_SERVICE: sssd

TEST_LDAP_USER: mattd-test01
